/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#94d3c1",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#6d382a",
        "on-tertiary-container": "#e89f8c",
        "surface-variant": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "outline": "#707975",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#66ff8e",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#370e04",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed-dim": "#ffb5a1",
        "error-container": "#ffdad6",
        "on-surface-variant": "#3f4945",
        "on-surface": "#191c1e",
        "tertiary": "#4e2013",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-container": "#007232",
        "surface": "#f7f9fb",
        "on-primary-fixed": "#00201a",
        "inverse-surface": "#2d3133",
        "surface-container": "#eceef0",
        "tertiary-fixed": "#ffdbd1",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "background": "#f7f9fb",
        "on-primary-container": "#7ebdac",
        "secondary": "#006d2f",
        "surface-bright": "#f7f9fb",
        "error": "#ba1a1a",
        "outline-variant": "#bfc9c4",
        "secondary-fixed-dim": "#3de273",
        "surface-container-high": "#e6e8ea",
        "surface-tint": "#29695b",
        "primary-fixed": "#afefdd",
        "inverse-primary": "#94d3c1",
        "on-secondary-fixed": "#002109",
        "primary": "#00342b",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#065043",
        "primary-container": "#004d40",
        "on-secondary-fixed-variant": "#005322",
        "tertiary-container": "#693527",
        "secondary-container": "#5dfd8a"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "stack-sm": "8px",
        "container-padding": "24px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "gutter": "16px",
        "unit": "4px",
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "label-bold": ["Inter"],
        "headline-md-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"],
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
